library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = 'select * from file where Date in ("1/2/2007", "2/2/2007")', sep = ";")
date_time <- with(data, paste(Date, Time))
date_time <- strptime(date_time, "%d/%m/%Y %H:%M:%S")
data <- data.frame(data, date_time)
png(file = "plot2.png")
plot(data$date_time, data$Global_active_power, type = "l", bg = NA, xlab = NA, ylab = "Global Active Power (kilowatts)", xaxt = 'n')
axis(1, at = c(data$date_time[1],data$date_time[length(data$date_time)/2],data$date_time[length(data$date_time)]), labels = c("Thu", "Fri", "Sat"))
dev.off()